# Generated by Django 5.1.8 on 2025-04-07 00:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source_url', models.URLField(max_length=2000, verbose_name='Source URL')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('audio_format', models.CharField(choices=[('mp3', 'MP3'), ('aac', 'AAC'), ('wav', 'WAV'), ('flac', 'FLAC'), ('ogg', 'OGG'), ('m4a', 'M4A')], default='mp3', max_length=10, verbose_name='Format')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, verbose_name='File Path')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery Task ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction',
                'verbose_name_plural': 'Extractions',
                'ordering': ['-created'],
            },
        ),
    ]
